CREATE TABLE "congresspersons" (
  "id" integer PRIMARY KEY,
  "ppid" varchar,
  "title" varchar,
  "short_title" varchar,
  "api_uri" varchar,
  "first_name" varchar,
  "middle_name" varchar,
  "last_name" varchar,
  "suffix" varchar,
  "date_of_birth" date,
  "gender" varchar,
  "party" varchar,
  "leadership_role" varchar,
  "twitter_account" varchar,
  "facebook_account" varchar,
  "youtube_account" varchar,
  "govtrack_id" integer,
  "cspan_id" integer,
  "votesmart_id" integer,
  "icpsr_id" integer,
  "crp_id" varchar,
  "google_entity_id" varchar,
  "fec_candidate_id" varchar,
  "url" varchar,
  "rss_url" varchar,
  "contact_form" varchar,
  "in_office" boolean,
  "cook_pvi" varchar,
  "dw_nominate" float,
  "ideal_point" varchar,
  "seniority" integer,
  "next_election" integer,
  "total_votes" integer,
  "missed_votes" integer,
  "total_present" integer,
  "last_updated" datetime,
  "ocd_id" varchar,
  "office" varchar,
  "phone" varchar,
  "fax" varchar,
  "state" varchar,
  "district" integer,
  "at_large" boolean,
  "geoid" integer,
  "senate_class" integer,
  "state_rank" varchar,
  "lis_id" varchar,
  "missed_votes_pct" float,
  "votes_with_party_pct" float,
  "votes_against_party_pct" float
);

CREATE TABLE "congress" (
  "id" integer PRIMARY KEY,
  "congress_number" integer,
  "member_id" integer,
  "senate" boolean,
  "house" boolean
);

ALTER TABLE "congress" ADD FOREIGN KEY ("member_id") REFERENCES "congresspersons" ("id");
